language: generic
sudo: required
services:
  - docker


before_install:
  - docker build -t Servetkot/docker-react -f Dockerfile.dev .
  
script:
  - docker run -e CI=true Servetkot/docker-react npm run test